# Generated by Django 2.0.4 on 2018-04-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='account',
            new_name='student',
        ),
    ]
